Lab02-JoseAlvarez-OscarLemus/Lab02-JoseAlvarez-OscarLemus/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lab02_JoseAlvarez_OscarLemus.Models
{
    public class Invoice
    {
        //Random number
        [Required]
        [DisplayName("Serie")]
        public string serial { get; set; }

        [Required]
        [DisplayName("Correlativo")]
        public string correlative { get; set; }

        [Required]
        [DisplayName("Cliente")]
        public string customer { get; set; }

        [Required]
        [DisplayName("NIT")]
        public string NIT { get; set; }

        [Required]
        [DisplayName("Fecha")]
        public string date { get; set; }

        //The products must exist
        [Required]
        [DisplayName("Descripión de compra")]
        public string purchaseDescription { get; set; }

        [Required]
        [DisplayName("Total")]
        public string total { get; set; }


        // With Random Serial
        public Invoice(string correlative, string customer, string NIT, string date, string purchaseDescription, string total)
        {
            this.serial = (new Random().Next(1, 1000)).ToString();
            this.correlative = correlative;
            this.customer = customer;
            this.NIT = NIT;
            this.date = date;
            this.purchaseDescription = purchaseDescription;
            this.total = total;
        }


        // With Not Random Serial
        public Invoice(string serial, string correlative, string customer, string NIT, string date, string purchaseDescription, string total)
        {
            this.serial = serial;
            this.correlative = correlative;
            this.customer = customer;
            this.NIT = NIT;
            this.date = date;
            this.purchaseDescription = purchaseDescription;
            this.total = total;
        }


        public static int compareInvoices(Invoice x, Invoice y)
        {
            //if (y == null)
            //    return 1;
            //else if (int.Parse(x.serial + x.correlative) > int.Parse(y.serial + y.correlative).Normalize())
            //    return 1;
            //else if (int.Parse(x.serial + x.correlative) < int.y.serial + y.correlative)
            //    return -1;
            //else
            //    return 0;
            return (x.serial + x.correlative).CompareTo(y.serial + y.correlative);
        }
    }
}

Lab02-JoseAlvarez-OscarLemus/Lab02-JoseAlvarez-OscarLemus/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab02_JoseAlvarez_OscarLemus.Extras;
using Lab02_JoseAlvarez_OscarLemus.Models;
using System.IO;

namespace Lab02_JoseAlvarez_OscarLemus.Controllers
{
    public class InvoiceController : Controller
    {
        // GET: Invoice
        public ActionResult Index()
        {
            BinaryTree<Invoice> InvoiceTree;
            // If there's already a tree, we work on it. Otherwise, we create a new one.
            if (Session["InvoiceTree"] != null)
                InvoiceTree = (BinaryTree<Invoice>)Session["InvoiceTree"];
            else
                InvoiceTree = new BinaryTree<Invoice>();

            // Session["ProductsTree"] will be considered null if there's no item in the tree
            if (InvoiceTree.Size() == 0)
                Session["InvoiceTree"] = null;
            else
                Session["InvoiceTree"] = InvoiceTree;

            return View(Session["ProductsTree"]);
        }


        // GET: Invoice/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Invoice/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            BinaryTree<Invoice> InvoiceTree = (BinaryTree<Invoice>)Session["InvoiceTree"];

            string purchaseDescription = Request.Form[0];
            Session["InvoiceTree"] = InvoiceTree;
            return RedirectToAction("Index", Session["InvoiceTree"]);
        }




        [HttpPost] //Since user is retrieving data
        public ActionResult ReadInvoice(HttpPostedFileBase uploadedFile)
        {
            BinaryTree<Invoice> InvoiceTree;
            // If there's already a tree, we work on it. Otherwise, we create a new one.
            if (Session["InvoiceTree"] != null)
                InvoiceTree = (BinaryTree<Invoice>)Session["InvoiceTree"];
            else
                InvoiceTree = new BinaryTree<Invoice>();


            if (uploadedFile == null)
                return View("Index");

            StreamReader reader = new StreamReader(uploadedFile.InputStream);
            string line = "";

            if (uploadedFile != null && uploadedFile.ContentLength > 0)
            {
                while ((line = reader.ReadLine()) != null)
                {
                    var information = line.Split(',');

                    Invoice InvoiceObj = null;
                    if (information.Length == 7) //means there's specific serial in the parameters
                    {
                        int total = -1;
                        //Data validation
                        try
                        {
                            total = int.Parse(information[6]);
                        }
                        catch (Exception)
                        {
                        }
                        InvoiceObj = new Invoice(information[0], information[1], information[2], information[3], information[4], information[5], information[6]);
                    }
                    else if (information.Length == 6) // means no serial in the parameteres, there will be a random one.
                    {
                        int total = -1;
                        //Data validation
                        try
                        {
                            total = int.Parse(information[7]);
                        }
                        catch (Exception)
                        {
                        }
                        InvoiceObj = new Invoice(information[0], information[1], information[2], information[3], information[4], information[5]);
                    }

                    InvoiceTree.Insert(InvoiceObj, (Invoice x, Invoice y) => (x.serial + x.correlative).CompareTo(y.serial + y.correlative));

                }
            }

            Session["InvoiceTree"] = InvoiceTree;
            return View("Index", Session["InvoiceTree"]);

        }

        public ActionResult Add(string serial, string correlative, string customer, string NIT, string date, string purchaseDescription, string total)
        {
            BinaryTree<Invoice> InvoiceTree;
            if (Session["InvoiceTree"] != null)
                InvoiceTree = (BinaryTree<Invoice>)Session["InvoiceTree"];
            else
                InvoiceTree = new BinaryTree<Invoice>();

            Invoice InvoiceObj = null;
            if (serial != null)
                InvoiceObj = new Invoice(serial, correlative, customer, NIT, date, purchaseDescription, total);
            else
                InvoiceObj = new Invoice(correlative, customer, NIT, date, purchaseDescription, total);

            InvoiceTree.Insert(InvoiceObj, Invoice.compareInvoices);

            Session["InvoiceTree"] = InvoiceTree;
            return View("Index", Session["InvoiceTree"]);





        }



    }






}

Lab02-JoseAlvarez-OscarLemus/Lab02-JoseAlvarez-OscarLemus/Views/Invoice/Index.cshtml
@model IEnumerable<Lab02_JoseAlvarez_OscarLemus.Models.Invoice>
@{
    ViewBag.Title = "Index";
}

<h2>Facturas</h2>


@using (Html.BeginForm("ReadInvoice", "Invoice", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="uploadedFile"/>
    <br />
    <button type="submit">Subir Archivo</button>
    <br />
}

<br />

@using (Html.BeginForm("Add", "Invoice", FormMethod.Post))
{
    <label>Serial (puede dejarlo vacio y se generará aleatoriamente)</label>
    <br/>
    <input type="text" name="serial" id="serial" />

    <br />
    <label>Correlativo</label>
    <br />
    <br />
    <input type="text" name="correlative" id="correlative"/>
    <br />
    
    <label>Cliente</label>
    <br />
    <input type="text" name="customer" id="customer"/>
    <br />

    <br />
    <label>NIT</label>
    <br />
    <input type="text" name="NIT" id="NIT"/>
    <br />

    <br />
    <label>Fecha</label>
    <br />
    <input type="text" name="date" id="date" />
    <br />

    <br />
    <label>Descripción de compra</label>
    <br />
    <input type="text" name="date" id="date" />

    <br />
    <label>Total</label>
    <br />
    <input type="text" name="total" id="total" />
    <br />

    <button type="submit">Agregar producto</button>



}





@if (Session["InvoiceTree"] != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.purchaseDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.customer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.purchaseDescription)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.total)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.serial })  |
                    @Html.ActionLink("Details", "Details", new { id = item.serial }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.serial })
                </td>
            </tr>
        }

    </table>
}
else
{
    <h3>No hay datos</h3>
}